// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABgZZRNWIJZiiaVoRaFMmg2VlA4LW8rCk',
    appId: '1:904983470069:web:c3e15acec598bb23accabc',
    messagingSenderId: '904983470069',
    projectId: 'flutterproductorder',
    authDomain: 'flutterproductorder.firebaseapp.com',
    storageBucket: 'flutterproductorder.appspot.com',
    measurementId: 'G-1NRH4Q1NX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm_Z48VhR63gSFaGRbxl2F6yJW15-UYbk',
    appId: '1:904983470069:android:a826d7058d022b38accabc',
    messagingSenderId: '904983470069',
    projectId: 'flutterproductorder',
    storageBucket: 'flutterproductorder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOOWOsVFkrBQ0PXq3Xca7H8Q8w0Y2sRWY',
    appId: '1:904983470069:ios:a0cb3b7c29b8b185accabc',
    messagingSenderId: '904983470069',
    projectId: 'flutterproductorder',
    storageBucket: 'flutterproductorder.appspot.com',
    iosBundleId: 'com.example.shoppingPractiseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOOWOsVFkrBQ0PXq3Xca7H8Q8w0Y2sRWY',
    appId: '1:904983470069:ios:8b05f4a535c05fceaccabc',
    messagingSenderId: '904983470069',
    projectId: 'flutterproductorder',
    storageBucket: 'flutterproductorder.appspot.com',
    iosBundleId: 'com.example.shoppingPractiseProject.RunnerTests',
  );
}
